# Base configuration

#theme: jekyll-theme-minimal
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "midnight" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-remote-theme
- jekyll-sitemap        # Jekyll plugin to silently generate a sitemaps.org compliant sitemap for your Jekyll site.
- jekyll-gist 	        # Liquid tag for displaying GitHub Gists in Jekyll sites.
- jekyll-feed 	        # A Jekyll plugin to generate an Atom (RSS-like) feed of your Jekyll posts.
- jekyll-include-cache  # Liquid tag that caches Liquid includes.

# whitelist:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-include-cache

# Reading Files
include:
  - .htaccess
  - pages
exclude:
  - _______
  # - assets/js/plugins
  # - assets/js/_main.js
  # - assets/js/vendor
  - Gemfile

# Sass/SCSS
sass:
  sass_dir: _sass/minimal-mistakes
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

#color_scheme: midnight

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: C
    block:
      line_numbers: false
  # input: GFM
  # hard_wrap: false
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false

permalink: pretty

#color_scheme: dark



# Title
#name: DCgov Guides Template

# Author/Organization info to be displayed in the templates
# author:
#   name: Office of the Chief Technology Officer
#   url: http://octo.dc.gov


# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
# logourl: /assets/img/dc_logo.png
# logoalt: The D.C. flag


# collections:
#   chapter_0:
#     permalink: "/:collection/:path/"
#     output: true
#   chapter_1:
#     permalink: "/:collection/:path/"
#     output: true
# 
# syslog_ng_docs:
#     collections:
#       chapter_0:
#         name: Installation
#         nav_fold: true
#       chapter_1:
#         name: Structure
#         nav_fold: false


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc_sticky: true
      #author_profile: true
      sidebar:
        nav: "main"



search: true #, false (default)
search_full_content: true #, false (default)

search_provider: lunr
lunr:
  search_within_pages: true

# search_provider: algolia
# algolia:
#   application_id: # YOUR_APPLICATION_ID
#   index_name: # YOUR_INDEX_NAME
#   search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
#   powered_by: # true (default), false
 

atom_feed:
  hide: true #, false (default)

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment



# Enable or disable the site search
# Supports true (default) or false
# search_enabled: true
# search:
#   # Split pages into sections that can be searched individually
#   # Supports 1 - 6, default: 2
#   heading_level: 2
#   # Maximum amount of previews per search result
#   # Default: 3
#   previews: 2
#   # Maximum amount of words to display before a matched word in the preview
#   # Default: 5
#   preview_words_before: 3
#   # Maximum amount of words to display after a matched word in the preview
#   # Default: 10
#   preview_words_after: 3
#   # Set the search token separator
#   # Default: /[\s\-/]+/
#   # Example: enable support for hyphenated search words
#   tokenizer_separator: /[\s/]+/
#   # Display the relative url in search results
#   # Supports true (default) or false
#   rel_url: true
#   # Enable or disable the search button that appears in the bottom right corner of every page
#   # Supports true or false (default)
#   button: false














# Navigation
# List links that should appear in the site sidebar here
# navigation:
# - text: Introduction
#   internal: true
#   url: ./
# - text: Add a new page
#   internal: true
#   url: add-a-new-page
# - text: Configure the Guide
#   internal: true
#   url: configure-the-guide
# - text: GitHub Setup
#   internal: true
#   url: github
# - text: Create a Glossary
#   glossary: true
# - text: Edit this Repo
#   internal: false
#   url: https://github.com/DCgov/guides-template

# Repo list
# List repos that you would like to appear on the homepage here
# repos:
# - name: guides-template
#   description:
#   url: https://github.com/DCgov/guides-template
#
# google_analytics_ua:

# Style Variables
# brand_color: "#DA253B"



# For copy button on code
# enable_copy_code_button: true
