# Base configuration

remote_theme: mmistakes/minimal-mistakes@4.24.0
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "midnight" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Disable caching of content to disk in order to skip creating a .jekyll-cache or similar directory
disable_disk_cache: true

# If you’re publishing on GitHub Pages you should update only your _config.yml as GitHub Pages doesn’t load plugins via Bundler.
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap        # Jekyll plugin to silently generate a sitemaps.org compliant sitemap for your Jekyll site.
  - jekyll-gist 	        # Liquid tag for displaying GitHub Gists in Jekyll sites.
  - jekyll-include-cache  # Liquid tag that caches Liquid includes.

# Whitelist plugins under safe mode.
whitelist:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# NOTE: Overiding theme defaults https://jekyllrb.com/docs/themes/#overriding-theme-defaults
#       Jekyll will look first to your site’s content before looking to the theme’s defaults for any requested file in the following folders:
#         /assets
#         /_data
#         /_layouts
#         /_includes
#         /_sass
#source: doc

# Reading Files
#
# Every file or directory beginning with the following characters: 
#     ., _ , # or ~ 
# in the source directory will not be included in the destination folder. Such paths will have to be explicitly specified via the config file in the 
# include directive to make sure they’re copied over
# In Jekyll 3, the `exclude` configuration option replaces the default exclusion list.
# In Jekyll 4, user-provided entries get added to the default exclusion list instead and the `include` option can be used to override the default exclusion list entries.
#
include:
  - .htaccess
  # - assets/js/main.min.js
  # - assets/css
  # - assets/images
exclude:
  - README.md # The one in the root belongs to the GitHub repository page, not to the generated final site, use index.md
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  # - assets
  - .serve
  - .reftime
  - .vendor/
  - .bundle
  - .asset-cache
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - LICENSE.minimal-mistakes

# Sass/SCSS
sass:
  sass_dir: _sass/minimal-mistakes
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Note: If you assign footer_scripts the theme’s /assets/js/main.min.js file will be deactivated. 
#       This script includes jQuery and various other plugins that you’ll need to find replacements for and include separately.
#       https://mmistakes.github.io/minimal-mistakes/docs/javascript/
#
#footer_scripts:

# ------------------------------------------------------------

# Title
title: syslog-ng documentation
masthead_title: syslog-ng documentation

# Author/Organization info to be displayed in the templates
author:
  name: OpenSource Community
  url: https://github.com/syslog-ng/syslog-ng


# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: /doc

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
# logourl: /assets/img/dc_logo.png
# logoalt: The D.C. flag

# collections:
#   chapter_0:
#     permalink: "/:collection/:path/"
#     output: true
#   chapter_1:
#     permalink: "/:collection/:path/"
#     output: true
# 
# syslog_ng_docs:
#     collections:
#       doc-guide:
#         name: Documentation
#       admin-guide:
#         name: Administration
#       dev-guide:
#         name: Development

collections:
  doc:
    # Do not use :collection the GitHub forced project name we use as collection name and root
    #permalink: "/:collection/:path/"
    permalink: "/:path"
    output: true


# Global defult permalink format
# https://jekyllrb.com/docs/permalinks/
# GitHub project name we use as collection name and root
#permalink: /:path/
# NOTE: the above is always expanded like this, for collections it seems (note mentioned correctly in the documentataion)
#permalink: /:collection/:path/:basename
#paginate_path: /page:num/

# Defaults
defaults:
  # All pages
  - scope:
      # type: pages
      path: "" # an empty string here means all files in the project
    values:
      layout: single
      toc: true
      toc_sticky: true
      sidebar:
        nav: ""
  #
  # FIXME: The goal here would be to eliminate the now required "##permalink: :path/:name " in each folder README.md
  #        I guess this is a Jekyll bug 
  #        Using permalink rules here leds to an invisible navigation left sidebar
  # 
  # - scope:
  #     # type: pages
  #     path: "**/README.md"
  #   values:
  #     #permalink: :path/:name # /:collection does not work at this level ?!?!
  # - scope:
  #     # type: pages
  #     path: "**/index.md"
  #   values:
  #     #permalink: :path/:name
  #
  # Documentation guide _pages
  - scope:
      # NOTE: type can be a collection name
      type: doc
      # NOTE: path is real file system path, not permalinks
      path: "*/doc-guide/*"
    values:
      sidebar:
        nav: "doc-guide-nav"
  # Administrator guide _pages
  - scope:
      # NOTE: type can be a collection name
      type: doc
      # NOTE: path is real file system path, not permalinks
      path: "*/admin-guide/*"
    values:
      sidebar:
        nav: "admin-guide-nav"
  # Developer guide _pages
  - scope:
      # NOTE: type can be a collection name
      type: doc 
      # NOTE: path is real file system path, not permalinks
      # TODO: find a better filter, it is considered too slow
      path: "*/dev-guide/*"
    values:
      sidebar:
        nav: "dev-guide-nav"

# Search settings
search: true
search_full_content: true

search_provider: lunr
lunr:
  search_within_pages: true

# search_provider: algolia
# algolia:
#   application_id: # YOUR_APPLICATION_ID
#   index_name: # YOUR_INDEX_NAME
#   search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
#   powered_by: # true (default), false
 
# Markdown and sytax higlighting
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge # default
  syntax_highlighter_opts:
    default_lang: C
    guess_lang: true
    block:
      line_numbers: false
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  footnote_nr: 1
  # entity_output: as_char
  # enable_coderay: false

atom_feed:
  hide: true

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# These are introduced with our customized theme source, not part of mmistakes/minimal-mistakes

# Option to add copy button to Code blocks
enable_copy_code_button: true

# Option to set the width of the page inner content part
# Any max-with css value, theme default is $max-width that is $x-large: 1280px in _variables.scss
page_content_width: 90%

sidebar:
  sticky: true
  nav_sub_items_scaled: true
  nav_sub_items_ident: 0.25em

masthead:
  # Option to hide masthead navigator in the page top bar
  hide_navigator: true
  # Option to make the masthead page top bar sticky
  sticky: true

footer:
  top_margin: 2em # originally 3em, needed if there are visible prev/next navigator buttons
