# Base configuration

remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "midnight" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-remote-theme
- jekyll-sitemap        # Jekyll plugin to silently generate a sitemaps.org compliant sitemap for your Jekyll site.
- jekyll-gist 	        # Liquid tag for displaying GitHub Gists in Jekyll sites.
- jekyll-include-cache  # Liquid tag that caches Liquid includes.

# whitelist:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-include-cache

# Reading Files
include:
  - .htaccess
exclude:
  - _______
  # - assets/js/plugins
  # - assets/js/_main.js
  # - assets/js/vendor
  - Gemfile

# Sass/SCSS
sass:
  sass_dir: _sass/minimal-mistakes
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Title
#name: syslog-ng documentation
masthead_title: syslog-ng documentation

# Author/Organization info to be displayed in the templates
author:
  name: OpenSource Community
  url: https://github.com/syslog-ng/syslog-ng


# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
# logourl: /assets/img/dc_logo.png
# logoalt: The D.C. flag

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc_sticky: true
      #author_profile: true
      sidebar:
        nav: "main"

# Deafult permalink format
# https://jekyllrb.com/docs/permalinks/
permalink: /:categories/:path/:basename
paginate_path: /page:num/

# collections:
#   chapter_0:
#     permalink: "/:collection/:path/"
#     output: true
#   chapter_1:
#     permalink: "/:collection/:path/"
#     output: true
# 
# syslog_ng_docs:
#     collections:
#       chapter_0:
#         name: Installation
#         nav_fold: true
#       chapter_1:
#         name: Structure
#         nav_fold: false

# Search settings
search: true
search_full_content: true

search_provider: lunr
lunr:
  search_within_pages: true

# search_provider: algolia
# algolia:
#   application_id: # YOUR_APPLICATION_ID
#   index_name: # YOUR_INDEX_NAME
#   search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
#   powered_by: # true (default), false
 
# Markdown and sytax higlighting
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: C
    block:
      line_numbers: false
  # input: GFM
  # hard_wrap: false
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false

atom_feed:
  hide: true

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# These are introduced with our customized theme source, not part of mmistakes/minimal-mistakes

# Option to add copy button to Code blocks
enable_copy_code_button: true

# Option to set the width of the page inner content part
# Any max-with css value, theme default is $max-width that is $x-large: 1280px in _variables.scss
page_content_width: 90%

# Option to hide masthead navigator in the page top bar
hide_masthead_navigator: true
